http:
  port: "8081"
  
american:
  host: "training4-american-new-api-megha.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "8a4d9372f9ff45578ed7a4660680f466"
  client_secret: "99b6a6BfC42B4ad1B24F95c0744BaD7F"
  
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"